# https://pre-commit.com/
# pre commit hooks for python
# install with:
# pip install pre-commit
# pre-commit install
# pre-commit run --all-files

# ruff and mypy just run on some files, due to the nature of the codebase
# somehow `noqa` is not working for some reason, thus ignoring globally, should be checked from time to time
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff
        args: [--fix, --ignore=E721, --ignore=F403, --ignore=E402]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.2
    hooks:
      - id: uv-lock
